# Generated by Django 3.0.2 on 2020-05-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title']},
        ),
    ]
