# Generated by Django 3.0.2 on 2020-05-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyapitoken',
            name='token_did_expire',
        ),
    ]
