# Generated by Django 3.0.2 on 2020-05-10 14:13

import artist.models.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=artist.models.functions.artist_image_file_path),
        ),
    ]
